BATTERY = 24

MOTOR_LEFT_1 = 13
MOTOR_LEFT_2 = 11
MOTOR_RIGHT_1 = 16
MOTOR_RIGHT_2 = 18

DISTANCE_MID_TRIG = 22
DISTANCE_MID_ECHO = 12
DISTANCE_LEFT_ECHO
DISTANCE_LEFT_TRIG
DISTANCE_RIGHT_ECHO
DISTANCE_LEFT_TRIG